### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Araly** [librevixen/LibreVixen#7]
Hello,

First I want to address having lurked around for a while, looking at LibreFox and the motivation for the fork.

what I'm really here for is asking how usable librefox is, as it's two versions behind firefox (but apparently it shouldn't be an issue)

and all this is really an excuse to say hello, give my good lucks for the project, hopefully it can take back where LibreFox had to stop. I'll maybe try to help a bit too, if I find time

**Comment by BeatLink** [comment]
Things are just starting up, so unfortunately, a full release is not available as yet, but it will be available very soon (around the end of next week if not sooner). The first couple of releases however will be based on Firefox nightly, so it should be even more up to date than the main Firefox version.

**Comment by BeatLink** [comment]
I'll go ahead and close this issue. If you have any feature requests, thoughts and suggestions, let us know here! For progress of the project, you can track issue #1
